Desktop version
beyk/Portfolio-mobile-version pull request #5
Opened 2022-01-21 16:34 UTC by beyk

I use media queries to make sure that my website displays correctly on desktop screens.

2022-01-21 17:08 UTC, Rustamxon7 requested changes
Hi @beyk , 

Good job so far!

### HIGHLIGHTS!

- No linters errors.💯
- Descriptive Readme.md. 💯


There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-21 17:08 UTC, rustam-tolipov commented on styles/desk-style.css
> +
## YOU DID A NICE JOB SO FAR 🎊👏

- [ ] However, there are some requirements that need to be fixed. If you follow all suggestion I gave you should be accepted by the next reviewer 💻🍀. In your hero section please add some more padding to the bottom to stick the Figma design 👌

#### Your design
![image](https://user-images.githubusercontent.com/69011963/150567687-6334656b-6193-414b-aa4f-62ecba678685.png)

#### Figma design, please ignore the yellow line. It means someone also making their portfolo. ok 😜?
![image](https://user-images.githubusercontent.com/69011963/150567778-aee664ce-6b26-4c64-9877-be5fb233042b.png)

2022-01-21 17:08 UTC, Rustamxon7 commented on styles/desk-style.css
> +  }
- [ ] There is too much space than it needs to be between the content of the work card. Please see the images below and decrease spacing in 3 places as I showed you 🤗

#### Your design
![image](https://user-images.githubusercontent.com/69011963/150568532-09a186a2-e816-436e-ae41-d5e37099a005.png)

2022-01-21 17:08 UTC, Rustamxon7 commented on styles/desk-style.css
> +  }
- [ ] And finally, in the about section columns are not aligned in one line and there is a typo. Please make both sides in one line (marked with pink line) and of course don't forget to change `langguages` to `Languages` (marked with lime line). That's it, please fix all the mentioned issues, **good luck 🍀**

#### Screenshot the marks
![image](https://user-images.githubusercontent.com/69011963/150569458-e17878d2-04f8-44d2-a59a-fc23433db343.png)

2022-01-22 07:30 UTC, brytebee requested changes
Hi, @beyk👋, 

Great work on making the changes 👏 👏 
You've done well implementing some of the requested changes requested by the previous review, but there are still some which aren't addressed yet.


# Suggested changes
_Check the comments under the review._

![](https://media.giphy.com/media/VlqzeaRnhCvPLfrSh6/giphy.gif)


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2022-01-22 07:30 UTC, brytebee commented on index.html
> +						<a href="#">LET’S CONNECT</a>
- [ ] **Required:** You are required to have a clone of the template as the previous reviewer has said. I observed the follow 

Your design | Figma template
:---: | :---:
![image](https://user-images.githubusercontent.com/27709832/150628894-0035f993-2d80-4149-b497-2b5130dd34a6.png) | ![image](https://user-images.githubusercontent.com/27709832/150628912-76df331c-1313-4ed7-80d9-a09f903a5822.png)

All font-family should be Poppins. Let's make the change 👍 

- [ ] **Required:** Let's make the alignment similar as well on the card of projects and others, the language section should be aligned properly and the button in the contact section should be centred like all other elements in the section.

Your design | Figma template
:---: | :---:
![image](https://user-images.githubusercontent.com/27709832/150629086-e74f16b4-ae9b-4793-ab31-e2540640d001.png) | ![image](https://user-images.githubusercontent.com/27709832/150629113-17c2706c-cc20-469f-be84-ee65de941108.png)
![image](https://user-images.githubusercontent.com/27709832/150629167-952f5041-3390-4c22-9806-39be58526486.png) | ![image](https://user-images.githubusercontent.com/27709832/150629197-9f7920b8-c1c2-4702-a31b-6bbf5780906c.png)
![image](https://user-images.githubusercontent.com/27709832/150629278-ab05be49-3664-49b1-b127-244b168ff0cf.png) | ![image](https://user-images.githubusercontent.com/27709832/150629291-ddc69dd2-c0fd-4512-86ab-2420d371bc3b.png)

2022-01-22 08:15 UTC, brytebee approved these changes
Hi, @beyk 👋,

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-22 08:22 UTC, merged